name: "Matt's ramblings"
description: "Python projects, CS curiosities, and mathematical musings."

url: "http://matthewearl.github.io"

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments

gems:
  - jekyll
  - jekyll-feed

