name: "Matt's Ramblings"
description: "Python projects, CS curiosities, and mathematical musings."

url: "http://matthewearl.github.io"

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments
future: true

gems:
  - jekyll
  - jekyll-feed

